[package]
name = "poly"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
serde = { version = "1.0.137", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
serde_json = "1.0.81"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
